/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.commonwealthrobotics;

import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.Thread.UncaughtExceptionHandler;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;

import static com.neuronrobotics.bowlerstudio.scripting.DownloadManager.*;

import com.neuronrobotics.bowlerstudio.BowlerKernel;
import com.neuronrobotics.bowlerstudio.NameGetter;
import com.neuronrobotics.bowlerstudio.PsudoSplash;
import com.neuronrobotics.bowlerstudio.SplashManager;
import com.neuronrobotics.bowlerstudio.assets.AssetFactory;
import com.neuronrobotics.bowlerstudio.assets.ConfigurationDatabase;
import com.neuronrobotics.bowlerstudio.assets.FontSizeManager;
import com.neuronrobotics.bowlerstudio.assets.StudioBuildInfo;
import com.neuronrobotics.bowlerstudio.scripting.DownloadManager;
import com.neuronrobotics.bowlerstudio.scripting.GitHubWebFlow;
import com.neuronrobotics.bowlerstudio.scripting.PasswordManager;
import com.neuronrobotics.bowlerstudio.scripting.ScriptingEngine;
import com.neuronrobotics.bowlerstudio.scripting.external.GroovyEclipseExternalEditor;
import com.neuronrobotics.bowlerstudio.vitamins.AskToFixInterface;
import com.neuronrobotics.bowlerstudio.vitamins.Vitamins;
import com.neuronrobotics.nrconsole.util.FileSelectionFactory;
import com.neuronrobotics.sdk.common.Log;

import eu.mihosoft.vrl.v3d.CSG;
import eu.mihosoft.vrl.v3d.parametrics.CSGDatabase;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Rectangle2D;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.Screen;
import java.awt.*;
import java.io.IOException;
import javafx.application.Platform;
import javafx.stage.Stage;

import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {
	private static Thread loadDeps;
	public static UncaughtExceptionHandler hand;
	private static final String paramsKey = "CaDoodle-Configs";
	private static final String objectKey = "currentVersion";
	public static int screenRefreshRate = 60;

	@Override
	public void start(Stage stage) throws Exception {

		FXMLLoader loader = new FXMLLoader(Main.class.getResource("MainWindow.fxml"), ActiveProject.getLangaugePack());
		loader.setController(new MainController(stage));
		Parent root = loader.load();

		// Get JavaFX screen bounds (this already accounts for taskbars, etc.)
		Rectangle2D primaryScreenBounds = javafx.stage.Screen.getPrimary().getVisualBounds();

		double sw = primaryScreenBounds.getWidth();
		double sh = primaryScreenBounds.getHeight();

		// Create a smaller buffer to account for window decorations
		double w = sw; // Increased margin
		double h = sh;

		Scene scene = new Scene(root);
		PsudoSplash.setParentWindow(stage);
		stage.setScene(scene);

		stage.setWidth(w);
		stage.setHeight(h);

		// Explicitly disable fullscreen/maximized
		stage.setFullScreen(false);
		stage.setMaximized(false);

		String title = StudioBuildInfo.getAppName() + " v " + StudioBuildInfo.getVersion();
		if (stage != null)
			stage.setTitle(title);
		stage.setOnCloseRequest(event -> {
			Platform.exit();

			System.exit(0);
		});

		try {
			// CADoodle-Icon.png
			Image fxIcon = new Image(Main.class.getResourceAsStream("CADoodle-Icon.png"));

			stage.getIcons().add(fxIcon);

			// Set system taskbar/dock icon
			try {
				if (java.awt.Taskbar.isTaskbarSupported()) {
					java.awt.Taskbar taskbar = java.awt.Taskbar.getTaskbar();

					if (taskbar.isSupported(java.awt.Taskbar.Feature.ICON_IMAGE)) {
						// Convert JavaFX Image to AWT BufferedImage
						java.awt.image.BufferedImage awtIcon = javafx.embed.swing.SwingFXUtils.fromFXImage(fxIcon,
								null);
						taskbar.setIconImage(awtIcon);
					}
				}

				// Additional approach for Linux - set via AWT/Swing
				if (System.getProperty("os.name").toLowerCase().contains("linux")) {
					// This approach works better on some Linux desktop environments
					java.awt.image.BufferedImage awtIcon = javafx.embed.swing.SwingFXUtils.fromFXImage(fxIcon, null);

					// Force icon through AWT
					if (java.awt.Toolkit.getDefaultToolkit() != null) {
						// Create a hidden AWT frame to set the default icon
						final java.awt.Frame hiddenFrame = new java.awt.Frame();
						hiddenFrame.setIconImage(awtIcon);

						// Also try setting as default for all frames
						try {
							Class<?> xToolkit = Class.forName("sun.awt.X11.XToolkit");
							if (xToolkit.isInstance(java.awt.Toolkit.getDefaultToolkit())) {
								java.lang.reflect.Method method = xToolkit.getMethod("setIconImage",
										java.awt.Image.class);
								method.invoke(java.awt.Toolkit.getDefaultToolkit(), awtIcon);
							}
						} catch (Exception e) {
							// Reflection approach failed, not critical
						}
					}
				}
			} catch (Exception e) {
				com.neuronrobotics.sdk.common.Log.error(e);
			}

		} catch (Exception e) {
			com.neuronrobotics.sdk.common.Log.error(e);
		}
		FileSelectionFactory.setStage(stage);
		setupMeshFailPopup(stage);
		stage.show();

		// Get the screen refresh rate
		Screen screen = Screen.getScreensForRectangle(stage.getX(), stage.getY(), stage.getWidth(), stage.getHeight())
				.get(0);
		GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
		GraphicsDevice gd = ge.getScreenDevices()[Screen.getScreens().indexOf(screen)];
		Main.screenRefreshRate = gd.getDisplayMode().getRefreshRate();
		com.neuronrobotics.sdk.common.Log.debug("Screen refresh rate = " + Main.screenRefreshRate + " Hz");
	}

	public static int getScreenRefreshRate() {
		return screenRefreshRate;
	}

	public static void main(String[] args) {
		// Set WM_CLASS for GNOME to recognize the app
		if (System.getProperty("os.name").toLowerCase().contains("linux")) {
			// This must match StartupWMClass in the desktop file
			System.setProperty("glass.gtk.wmclass", "CADoodle");
		}
		String relative = ScriptingEngine.getWorkingDirectory().getAbsolutePath();
		File file = new File(relative + delim() + "CaDoodle-workspace" + delim());
		file.mkdirs();
		ScriptingEngine.setWorkspace(file);
		File logfile = new File(file.getAbsolutePath() + delim() + "cadoodleLog.txt");
		if (logfile.exists())
			logfile.delete();
		try {
			logfile.createNewFile();
			Log.enableDebugPrint(true);
			// Log.enableErrorPrint();
			Log.setFile(logfile);
			com.neuronrobotics.sdk.common.Log.debug("Log file set to " + logfile.getAbsolutePath());

			hand = new UncaughtExceptionHandler() {
				@Override
				public void uncaughtException(Thread t, Throwable e) {
					com.neuronrobotics.sdk.common.Log.error("Uncaught exception in " + t);
					com.neuronrobotics.sdk.common.Log.error(e);
				}
			};
			Thread.setDefaultUncaughtExceptionHandler(Main.hand);
			Platform.runLater(() -> {
				Thread.setDefaultUncaughtExceptionHandler(Main.hand);
			});
			Log.warning("CaDoodle Version " + StudioBuildInfo.getVersion());
			Runtime.getRuntime().addShutdownHook(new Thread(() -> {
				Log.debug("CaDoodle Exiting Clean");
				// Log.flush();
			}));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			com.neuronrobotics.sdk.common.Log.error(e);
		}
		// String currentVersionString = StudioBuildInfo.getVersion();
		String bindir = System.getProperty("user.home") + delim() + "bin" + delim() + "CaDoodle-ApplicationInstall"
				+ delim();
		String myVersionFileString = bindir + "currentversion.txt";
		// File myVersionFile = new File(myVersionFileString);
		// File bindirFile = new File(bindir);
		try {
			String myVersionString = new String(Files.readAllBytes(Paths.get(myVersionFileString))).trim();
			String currentVersionDir = bindir + myVersionString + delim();
			String zipGitCache = currentVersionDir + "gitcache.zip";
			File file2 = new File(zipGitCache);
			if (file2.exists()) {
				Log.debug("Git Cache zip exists " + zipGitCache);
				File workingDir = ScriptingEngine.getWorkspace();
				String workingGitCache = workingDir.getAbsolutePath() + delim() + "gitcache";
				// if(!new File(workingGitCache).exists()) {
				// Log.debug("Local GitCahe is missing: "+workingGitCache);
				try {
					unzip(file2, workingGitCache);
				} catch (Exception e) {
					Log.error(e);
				}
				// }
			} else {
				String lastVer = ConfigurationDatabase.get(paramsKey, objectKey, "0").toString();
				String nowVer = "" + StudioBuildInfo.getSDKVersion();
				boolean b = !lastVer.contentEquals(nowVer);
				boolean contentEquals = nowVer.contentEquals("0");
				boolean c = b || contentEquals;

				if (c) {
					// https://github.com/CommonWealthRobotics/CaDoodle-Git-Resources.git
					try {
						ScriptingEngine.gitScriptRun(CSGDatabase.getInstance(),
								"https://github.com/CommonWealthRobotics/CaDoodle-Git-Resources.git", "loadGit.groovy");
					} catch (Exception e) {
						Log.error(e);
					}
				}
			}
		} catch (IOException e) {
			Log.error(e);
		}

		DownloadManager.setSTUDIO_INSTALL("CaDoodle-ApplicationInstall");
		try {
			File jarFile = new File(GroovyEclipseExternalEditor.getApplicationJarPath());
			com.neuronrobotics.sdk.common.Log
					.debug("Application at " + jarFile + " is " + (jarFile.exists() ? "Found" : "Missing!"));
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			com.neuronrobotics.sdk.common.Log.error(e);
		}

		BowlerKernel.setKernelMode(false);
		if (args != null) {
			String all = "";
			for (String argument : args)
				all += argument + " ";

			String replace = all.replace('"', ' ').trim();
			com.neuronrobotics.sdk.common.Log.debug("Got command argument: \"" + replace + "\"");
			File f = new File(replace);
			com.neuronrobotics.sdk.common.Log.debug("Passed In File at " + f.getAbsolutePath());
			if (replace.toLowerCase().endsWith(".doodle")) {
				if (f.exists()) {
					ConfigurationDatabase.put("CaDoodle", "CaDoodleActiveFile", f.getAbsolutePath());
					com.neuronrobotics.sdk.common.Log.debug("Passed In File Exists! ");
					HashSet<String> externals = Main.getOptionalProjects();
					externals.add(f.getAbsolutePath());
					Main.saveOptionalProjects(externals);

				} else
					com.neuronrobotics.sdk.common.Log.debug("Fail! Passed In File Does Not Exists! ");
			} else
				com.neuronrobotics.sdk.common.Log.debug("Not a doodle file " + replace.toLowerCase());

		}
		PsudoSplash.setResource(Main.class.getResource("SourceIcon.png"));
		PsudoSplash.setTrayIcon(Main.class.getResource("CADoodle-Icon.png"));

		PsudoSplash.setTextColor(Color.BLACK);
		PsudoSplash.setVersionX(670);
		PsudoSplash.setVersionY(120);

		PsudoSplash.setLogX(250);
		PsudoSplash.setLogY(400);

		PsudoSplash.setMessageX(400);
		PsudoSplash.setMessageY(250);

		SplashManager.renderSplashFrame(1, "Main Window Show");

		ScriptingEngine.setAppName("CaDoodle");

		NameGetter mykey = new NameGetter();
		GitHubWebFlow.setName(mykey);
		try {
			PasswordManager.setupAnyonmous();
		} catch (IOException e) {
			// Auto-generated catch block
			com.neuronrobotics.sdk.common.Log.error(e);
		}
		if (PasswordManager.hasNetwork()) {
			try {
				ensureGitAssetsArePresent();
			} catch (Throwable t) {
				com.neuronrobotics.sdk.common.Log.error(t);
			}
		} else {
			SplashManager.renderSplashFrame(2, "No Network");
		}
		SplashManager.renderSplashFrame(2, "Images Loaded!");
		// com.neuronrobotics.sdk.common.Log.enableErrorPrint();
		FontSizeManager.getDefaultSize();
		CSG.setUseGPU(false);
		ActiveProject.getStyleSheetOptions();
		ActiveProject.getLangaugePack();
		Platform.runLater(new Runnable() {
			@Override
			public void run() {
				Thread.setDefaultUncaughtExceptionHandler((ex, source) -> {
					Log.error(ex);
				});
			}
		});
		String string = ConfigurationDatabase.get("CaDoodle", "DefaultNumberOfSides", "64").toString();
		try {
			int numberOfSidesInt = Integer.parseInt(string);
		} catch (Exception ex) {
			Log.error(ex);
			ConfigurationDatabase.put("CaDoodle", "DefaultNumberOfSides", "64");
		}

		try {
			launch();
		} catch (Exception ex) {
			Log.error(ex);
			Log.flush();
			ex.printStackTrace();
		}
	}

	private static void setupMeshFailPopup(Stage stage) {
		Vitamins.setAskToFix(new AskToFixInterface() {

			@Override
			public boolean tryToFix(File f, Throwable t) {
				return StlRepairDialogController.show(stage, f, t);
			}
		});
	}

	public static void saveOptionalProjects(HashSet<String> state) {
		ArrayList<String> l = (ArrayList<String>) ConfigurationDatabase.get("CaDoodle", "CaDoodleExternalOptions",
				new ArrayList<String>());
		l.clear();
		l.addAll(state);
		ConfigurationDatabase.put("CaDoodle", "CaDoodleExternalOptions", l);
		ConfigurationDatabase.save();
	}

	public static HashSet<String> getOptionalProjects() {
		ArrayList<String> l = (ArrayList<String>) ConfigurationDatabase.get("CaDoodle", "CaDoodleExternalOptions",
				new ArrayList<String>());
		HashSet<String> s = new HashSet<>();
		s.addAll(l);
		return s;
	}

	private static void ensureGitAssetsArePresent() {

		SplashManager.renderSplashFrame(2, "Load Image Assets...");

		String lastVer = ConfigurationDatabase.get(paramsKey, objectKey, "0").toString();
		String nowVer = "" + StudioBuildInfo.getSDKVersion();

		com.neuronrobotics.sdk.common.Log
				.debug("Pervious version was " + lastVer + " and current version is " + nowVer);
		ConfigurationDatabase.put(paramsKey, objectKey, nowVer);
		try {
			AssetFactory.loadAllAssets();
		} catch (Exception e) {
			// Auto-generated catch block
			com.neuronrobotics.sdk.common.Log.error(e);
		}
	}

	// public static Thread getLoadDeps() {
	// return loadDeps;
	// }
	//
	// public static void setLoadDeps(Thread loadDeps) {
	// Main.loadDeps = loadDeps;
	// }

}
